<h2>Recipes</h2>

<div id="recipecan_add_new_recipe">
    <h3>Add a new Recipe</h3>
    <a href="#" >Add a new Recipe</a>
</div>

<div id="recipecan_add_new_recipe_box" style="display: none;">
    <?php $this->render('admin/recipes/ajax/new'); ?>
</div>

<div id="recipecan_insert_existing_recipe_box">
    <h3>Use an existing Recipe</h3>
    <?php foreach($this->get('recipes') as $recipe) { ?>
        <div>
            <?php $this->p($recipe['name']); ?>
            <a data-recipe-name="<?php $this->p(str_replace("\"", "", $recipe['name'])); ?>"
               data-recipe-id="<?php $this->p($recipe['id']); ?>"
               href="#"
               class="recipecan_insert_recipe">Insert</a>
        </div>
    <?php } ?>
</div>
