
<div id="recipecan_loading" style="display: none;">

    <div class="recipecan_spinner">
        <img src="<?php echo $this->options['plugin_url']; ?>/images/loading.gif" />
    </div>
    <div class="recipecan_text">
        Saving Recipe.  This could take a minute, especially if you are uploading
        a photo.
    </div>

    <br class="recipecan_clean" />
</div>

<div id="recipecan_form_wrapper">
    <?php $this->render('shared/_form_errors'); ?>

    <form method="post" action="<?php echo $this->get('form_submit_url'); ?>" enctype="multipart/form-data" id="recipecan_new_recipe_form">

        <ul>
            <li>
                <label for="name">Name:</label><br />
                <input name="recipe[name]" id="name" value="<?php echo $this->get('recipe[name]'); ?>" size="32" />
            </li>

            <li>
                <label for="course">Course:</label><br />
                <select id="course" name="recipe[course]">
                    <option value=""></option>
                    <?php $courses = array(
                        "Breakfast", "Lunch", "Snack", "Appetizer", "Dinner", "Side",
                        "Drink", "Dessert"
                    );
                    foreach ($courses as $course) {
                        if ($course == $this->get('recipe[course]')) {
                            $selected = "selected";
                        } else {
                            $selected = "";
                        } ?>
                        <option value="<?php echo $course; ?>" <?php echo $selected; ?>><?php echo $course; ?></option>
                    <?php } ?>

                </select>
            </li>

            <li>
                <label for="cuisine">Cuisine:</label><br />
                <select id="cuisine" name="recipe[cuisine]">
                    <option value=""></option>
                    <?php $cuisines = array(
                        "American", "Cajun", "Chinese", "Cuban", "English", "Filipino",
                        "French", "German", "Greek", "Indian", "Irish", "Italian",
                        "Japanese", "Jewish", "Korean", "Mediterranean", "Mexican",
                        "Middle-Eastern", "Moroccan", "Polish", "Russian", "Southern",
                        "Spanish", "Thai", "Vietnamese"
                    );
                    foreach ($cuisines as $cuisine) {
                        if ($cuisine == $this->get('recipe[cuisine]')) {
                            $selected = "selected";
                        } else {
                            $selected = "";
                        } ?>
                        <option value="<?php echo $cuisine; ?>" <?php echo $selected; ?>><?php echo $cuisine; ?></option>
                    <?php } ?>

                </select>
            </li>

            <li>
                <label for="make_time">How long to make:</label><br />
                <input name="recipe[make_time]" id="make_time" value="<?php echo $this->get('recipe[make_time]'); ?>" size="18" />
            </li>

            <li>
                <label for="servings">Servings:</label><br />
                <input name="recipe[servings]" id="servings" value="<?php echo $this->get('recipe[servings]'); ?>" size="18" />
            </li>

            <li>
                <label for="tag_list">Tags:</label><br />
                <input name="recipe[tag_list]" id="tag_list" value="<?php echo $this->get('recipe[tag_list]'); ?>" size="48" />
            </li>

            <li>
                <label for="ingredients">Ingredients:</label><br />
                <textarea id="ingredients" name="recipe[ingredients]" cols="60" rows="8"><?php echo $this->get('recipe[ingredients]'); ?></textarea>
            </li>

            <li>
                <label for="directions">Directions:</label><br />
                <textarea id="ingredients" name="recipe[directions]" cols="60" rows="12"><?php echo $this->get('recipe[directions]'); ?></textarea>
            </li>

            <?php if ($this->get('form_photo')) { ?>
                <li>
                    <label  for="photo">Photo</label><br />
                    <input type="file" id="photo" name="photo" /><br/>
                </li>
            <?php } ?>

        </ul>

        <input class="button-primary" type="submit" name="Save" value="Save Recipe" id="submitbutton" />

    </form>
</div>