<?php $recipe = $this->get('recipe'); ?>

<h2>Edit <?php echo $recipe['name']; ?></h2>

<div id="recipecan_edit_recipe">
    <div class="recipecan_form">
        <?php
            $this->set('form_submit_url', '?page=recipecan_recipe&id=' . $recipe['id'] . '&method=put');
            $this->set('form_photo', false);
            $this->render('admin/recipes/_form');
        ?>
    </div>

    <div class="recipecan_photo">
        <?php if ($recipe['photo_large'] != '') { ?>
            <div>
                <a href="?page=recipecan_recipe_photo&id=<?php echo $recipe['id'] ?>">Change Photo</a>
            </div>
            <div>
                <img src="http://<?php echo $this->options['image_server']; ?><?php echo $recipe['photo_large']; ?>" alt="Recipe Photo" />
            </div>
        <?php } else { ?>
            <div>
                There is no photo for this recipe.
            </div>
            <div>
                <a href="?page=recipecan_recipe_photo&id=<?php echo $recipe['id'] ?>">Add Photo</a>
            </div>
        <?php } ?>
    </div>
    
</div>