<h2>Welcome to RecipeCan for Wordpress</h2>

<div id="recipecan_recipes_welcome">
    <div class="recipecan_image">
        <img src="<?php echo $this->options['plugin_url']; ?>/images/logo.png"
             alt="RecipeCan"
             height="100"
             width="223"
             />
    </div>
    <div class="recipecan_text">
        <div>Thank you for using RecipeCan for Wordpres.</div>
        <p>
            We are always looking for ways to improve this Wordpress
            plugin.  If you have any ideas
            <a href="http://www.recipecan.com/contact">please contact us</a>
            and we will be sure to get them added.
        </p>
    </div>
    <br class="recipecan_clear" />
</div>


<h2>Add a Recipe</h2>

You can <a href="?page=recipecan_new_recipe">add a recipe</a> to your blog at any
time.

<h2>Your Recipes</h2>
<table id="recipecan_table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Edit</th>
            <th>View</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach($this->get('recipes') as $recipe) { ?>
        <tr>
            <td><?php $this->p($recipe->get('name')); ?></td>
            <td><a href="?page=recipecan_edit_recipe&id=<?php $this->p($recipe->get('id')) ?>">Edit</a></td>
            <td><a href="<?php echo $recipe->link(); ?>">View</a></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

