<?php
    $recipe = $this->get('recipe');
?>

<h2>Recipe Photo</h2>

<?php if ($this->get('saved')) { ?>
    
    <h3>Saved</h3>
    <div>
        Your new recipe photo has been uploaded and saved
    </div>
    
<?php } ?>
<?php if ($this->get('error')) { ?>

    <h3>Errors</h3>
    <?php foreach ($this->get('error') as $field => $errors) { ?>
        <?php foreach ($errors as $error) { ?>
            <?php echo ucfirst($field); ?> <?php echo $error; ?>.<br />
        <?php } ?>
    <?php } ?>

<?php } ?>

<div id="file_uploading" style="display: none;">
    Your image file is uploading.  Please be patient as this process may take
    a minute or two.
</div>

<form 
    id="file_upload_form"
    action="?page=recipecan_recipe_photo&id=<?php echo $recipe['id']; ?>&method=post"
    method="post"
    enctype="multipart/form-data">
    Select a Photo: <input type="file" name="file" id="file"><br/>
</form>

<script>
    jQuery(document).ready(function() {

        jQuery('#file').change(function() {
            jQuery('#file_uploading').show();
            jQuery('#file_upload_form').submit().hide();
        });

    });
</script>

<?php if ($recipe['photo_large']) { ?>
    <div>
        <img src="http://<?php echo $this->options['imgage_server']; ?><?php echo $recipe['photo_large']; ?>" alt="Recipe Photo" />
    </div>
<?php } else { ?>
    <div>
        There is no photo for this recipe.
    </div>
<?php } ?>