<?php
    $display = $this->get('display');
?>

<div id="recipecan_recipes_<?php $this->p($display['name']); ?>">
    <h2><?php $this->p($display['title']); ?></h2>

    <?php if (count($display['recipes']) < 1) { ?>
        <div>
            There are currently no recipes.
        </div>
    <?php } ?>

    <?php foreach ($display['recipes'] as $recipe) { ?>
        <div class="recipecan_recipe_preview">

            <?php 
                if ($recipe->has_image()) {
                    $image = "http://" . $this->options['image_server'] . $recipe->get('photo_medium');
                } else { 
                    $image = $this->options['plugin_url'] . '/images/recipe/no_photo_preview.jpg'; 
                }
            ?>
            
            <div class="recipecan_image">
                <a href="<?php $this->p($recipe->link()); ?>"><img src="<?php $this->p($image); ?>" 
                    alt="<?php $this->p($recipe->safe_name()); ?> Recipe"
                    border="0" /></a>
            </div>

            <div class="recipecan_title">
                <h3><a href="<?php $this->p($recipe->link()); ?>"><?php $this->p($recipe->get('name')); ?></a></h3>
            </div>

        </div>
    <?php } ?>

    <br class="recipecan_clear" />

</div>
