<?php foreach($this->get('to_display') as $display_array) { ?>

    <div class="recipecan_list_recipes">
        <?php $this->display_recipes($display_array); ?>    
    </div>

<?php } ?>


<div id="recipecan_courses">

    <h2>Courses</h2>
    
    <?php foreach ($this->get('recipes')->courses() as $course) { ?>

        <div class="recipecan_course">
            <a href="<?php echo add_query_arg('search', strtolower($course), get_page_link($this->get('page_name'))); ?>"
                ><?php $this->p($course) ?></a>
        </div>

    <?php } ?>

    <br class="recipecan_clear" />
</div>

<div id="recipecan_search">

    <h2>Search Recipes</h2>

    <div>
        <form class="recipecan_form" action="<?php echo get_page_link($this->get('page_name')); ?>" method="post">
            <input class="recipecan_search_box" name="search" value="" maxlength="64" size="32" /> &nbsp;&nbsp;
            <input class="recipecan_submit" type="submit" value=" Search " />
        </form>
    </div>
    

</div>

